from __future__ import annotations

from datetime import date, datetime, timedelta, timezone
from typing import Any


PHASES = ("Initiation", "Planning", "Design", "Implementation", "Testing", "Validation", "Closure")

PHASE_KEYWORDS = {
    "Initiation": ("kickoff", "charter", "sponsor", "initiation", "mobilize"),
    "Planning": ("plan", "schedule", "scope", "baseline", "requirements", "approval"),
    "Design": ("design", "architecture", "solution", "blueprint"),
    "Implementation": ("build", "configure", "implement", "develop", "migrate", "deploy"),
    "Testing": ("test", "uat", "qa", "defect"),
    "Validation": ("validate", "acceptance", "sign-off", "signoff", "approve"),
    "Closure": ("close", "handover", "lessons", "transition", "closure"),
}


def generate_project_plan(file_id: str, analysis: dict[str, Any]) -> dict[str, Any]:
    base_start = infer_base_start(analysis.get("dates", []))
    assumptions = []
    if not analysis.get("dates"):
        assumptions.append("No explicit project dates found; placeholder dates start on the next Monday.")

    task_candidates = analysis.get("tasks") or tasks_from_deliverables(analysis)
    if not task_candidates:
        task_candidates = default_control_tasks()
        assumptions.append("No tasks found; default PMO control tasks were created as placeholders.")

    grouped = group_tasks_by_phase(task_candidates)
    rows: list[dict[str, Any]] = []
    current_start = base_start
    task_number = 0
    predecessor_wbs = ""

    for phase_index, phase in enumerate(PHASES, start=1):
        phase_tasks = grouped.get(phase, [])
        if not phase_tasks:
            continue

        phase_start = current_start
        phase_rows: list[dict[str, Any]] = []
        for item_index, task in enumerate(phase_tasks, start=1):
            task_number += 1
            duration = infer_duration_days(task)
            start_date = current_start
            end_date = start_date + timedelta(days=max(duration - 1, 0))
            dependency = predecessor_wbs if predecessor_wbs else ""
            wbs = f"{phase_index}.{item_index}"
            milestone = is_milestone(task)

            row = {
                "wbs_id": wbs,
                "phase": phase,
                "task_name": ensure_clear_name(task.get("name") or task.get("description") or "TBD Task"),
                "description": task.get("description") or task.get("name") or "TBD task description",
                "start_date": start_date.isoformat(),
                "end_date": end_date.isoformat(),
                "duration": "0d" if milestone else f"{duration}d",
                "duration_days": 0 if milestone else duration,
                "owner": task.get("owner") or "TBD Owner",
                "status": task.get("status") or "Not Started",
                "dependency_predecessor": dependency,
                "milestone": milestone,
                "notes": build_task_notes(task, analysis),
                "date_assumption": not bool(task.get("dates")),
            }
            phase_rows.append(row)
            rows.append(row)
            predecessor_wbs = wbs
            current_start = end_date if milestone else end_date + timedelta(days=1)

        rows.insert(
            len(rows) - len(phase_rows),
            {
                "wbs_id": str(phase_index),
                "phase": phase,
                "task_name": f"{phase} Phase",
                "description": f"Summary phase for {phase.lower()} work.",
                "start_date": phase_start.isoformat(),
                "end_date": phase_rows[-1]["end_date"],
                "duration": f"{sum(row['duration_days'] for row in phase_rows)}d",
                "duration_days": sum(row["duration_days"] for row in phase_rows),
                "owner": "TBD Owner",
                "status": rollup_status(phase_rows),
                "dependency_predecessor": "",
                "milestone": False,
                "notes": "Summary task generated by Ali PMO phase control.",
                "date_assumption": True,
            },
        )

    milestones = analysis.get("milestones", [])
    for index, milestone in enumerate(milestones[:5], start=1):
        task_number += 1
        milestone_date = current_start + timedelta(days=index * 3)
        rows.append(
            {
                "wbs_id": f"M{index}",
                "phase": "Milestones",
                "task_name": ensure_clear_name(milestone),
                "description": milestone,
                "start_date": milestone_date.isoformat(),
                "end_date": milestone_date.isoformat(),
                "duration": "0d",
                "duration_days": 0,
                "owner": "TBD Owner",
                "status": "Not Started",
                "dependency_predecessor": predecessor_wbs,
                "milestone": True,
                "notes": "Milestone extracted from source document.",
                "date_assumption": True,
            }
        )

    return {
        "file_id": file_id,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "project_title": analysis.get("project_title") or "TBD Project Title",
        "assumptions": assumptions,
        "missing_information": analysis.get("missing_information", []),
        "tasks": rows,
    }


def tasks_from_deliverables(analysis: dict[str, Any]) -> list[dict[str, Any]]:
    tasks = []
    for index, deliverable in enumerate(analysis.get("deliverables", []), start=1):
        tasks.append(
            {
                "id": f"DT{index:03d}",
                "name": f"Produce {deliverable}",
                "description": f"Create, review, and prepare acceptance for deliverable: {deliverable}",
                "owner": "TBD Owner",
                "status": "Not Started",
                "dependencies": [],
                "dates": [],
            }
        )
    return tasks


def default_control_tasks() -> list[dict[str, Any]]:
    names = [
        "Confirm project charter and sponsor approval",
        "Baseline scope, deliverables, and success criteria",
        "Develop integrated project schedule",
        "Execute delivery work packages",
        "Validate deliverables against acceptance criteria",
        "Complete handover and closure report",
    ]
    return [{"id": f"CT{index:03d}", "name": name, "description": name, "owner": "TBD Owner"} for index, name in enumerate(names, start=1)]


def group_tasks_by_phase(tasks: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    grouped = {phase: [] for phase in PHASES}
    fallback_index = 0
    for task in tasks:
        text = f"{task.get('name', '')} {task.get('description', '')}".lower()
        matched_phase = None
        for phase, keywords in PHASE_KEYWORDS.items():
            if any(keyword in text for keyword in keywords):
                matched_phase = phase
                break
        if not matched_phase:
            matched_phase = PHASES[min(fallback_index, len(PHASES) - 1)]
            fallback_index += 1
        grouped[matched_phase].append(task)
    return grouped


def infer_base_start(dates: list[str]) -> date:
    for value in dates:
        parsed = parse_date(value)
        if parsed:
            return parsed
    today = date.today()
    days_until_monday = (7 - today.weekday()) % 7
    if days_until_monday == 0:
        days_until_monday = 7
    return today + timedelta(days=days_until_monday)


def parse_date(value: str) -> date | None:
    formats = ("%Y-%m-%d", "%d/%m/%Y", "%m/%d/%Y", "%d-%m-%Y", "%m-%d-%Y", "%B %d %Y", "%b %d %Y", "%d %B %Y", "%d %b %Y")
    normalized = value.replace(",", "")
    for fmt in formats:
        try:
            return datetime.strptime(normalized, fmt).date()
        except ValueError:
            continue
    return None


def infer_duration_days(task: dict[str, Any]) -> int:
    text = f"{task.get('name', '')} {task.get('description', '')}"
    if is_milestone(task):
        return 0
    match = __import__("re").search(r"\b(\d+)\s*(?:day|days|d)\b", text, __import__("re").IGNORECASE)
    if match:
        return max(int(match.group(1)), 1)
    return 5


def is_milestone(task: dict[str, Any]) -> bool:
    text = f"{task.get('name', '')} {task.get('description', '')}".lower()
    return any(keyword in text for keyword in ("milestone", "approval", "sign-off", "signoff", "go-live", "launch"))


def ensure_clear_name(name: str) -> str:
    cleaned = " ".join(name.split()).strip(" -:|")
    if not cleaned:
        return "TBD Task"
    if len(cleaned) > 120:
        return cleaned[:117].rstrip() + "..."
    return cleaned


def build_task_notes(task: dict[str, Any], analysis: dict[str, Any]) -> str:
    notes = []
    if not task.get("owner"):
        notes.append("Owner assumed as TBD Owner.")
    if not task.get("dates"):
        notes.append("Dates are placeholder assumptions.")
    if task.get("dependencies"):
        notes.append("Dependency control phrase detected.")
    if analysis.get("acceptance_criteria"):
        notes.append("Validate against extracted acceptance criteria.")
    return " ".join(notes) or "Generated from source document."


def rollup_status(rows: list[dict[str, Any]]) -> str:
    statuses = {row["status"] for row in rows}
    if "At Risk" in statuses:
        return "At Risk"
    if statuses == {"Completed"}:
        return "Completed"
    if "In Progress" in statuses:
        return "In Progress"
    return "Not Started"
